// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.0
// source: cmd/webapi_grpc/proto/api.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContactHash   string                 `protobuf:"bytes,1,opt,name=contact_hash,json=contactHash,proto3" json:"contact_hash,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_cmd_webapi_grpc_proto_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_webapi_grpc_proto_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_cmd_webapi_grpc_proto_api_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageRequest) GetContactHash() string {
	if x != nil {
		return x.ContactHash
	}
	return ""
}

func (x *SendMessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_cmd_webapi_grpc_proto_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_webapi_grpc_proto_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_cmd_webapi_grpc_proto_api_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendMessageResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetContactsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContactsRequest) Reset() {
	*x = GetContactsRequest{}
	mi := &file_cmd_webapi_grpc_proto_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContactsRequest) ProtoMessage() {}

func (x *GetContactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_webapi_grpc_proto_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContactsRequest.ProtoReflect.Descriptor instead.
func (*GetContactsRequest) Descriptor() ([]byte, []int) {
	return file_cmd_webapi_grpc_proto_api_proto_rawDescGZIP(), []int{2}
}

type GetContactsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contacts      []*Contact             `protobuf:"bytes,1,rep,name=contacts,proto3" json:"contacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContactsResponse) Reset() {
	*x = GetContactsResponse{}
	mi := &file_cmd_webapi_grpc_proto_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContactsResponse) ProtoMessage() {}

func (x *GetContactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_webapi_grpc_proto_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContactsResponse.ProtoReflect.Descriptor instead.
func (*GetContactsResponse) Descriptor() ([]byte, []int) {
	return file_cmd_webapi_grpc_proto_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetContactsResponse) GetContacts() []*Contact {
	if x != nil {
		return x.Contacts
	}
	return nil
}

type Contact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	IsOnline      bool                   `protobuf:"varint,3,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contact) Reset() {
	*x = Contact{}
	mi := &file_cmd_webapi_grpc_proto_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_webapi_grpc_proto_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_cmd_webapi_grpc_proto_api_proto_rawDescGZIP(), []int{4}
}

func (x *Contact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Contact) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Contact) GetIsOnline() bool {
	if x != nil {
		return x.IsOnline
	}
	return false
}

type GetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContactHash   string                 `protobuf:"bytes,1,opt,name=contact_hash,json=contactHash,proto3" json:"contact_hash,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_cmd_webapi_grpc_proto_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_webapi_grpc_proto_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_cmd_webapi_grpc_proto_api_proto_rawDescGZIP(), []int{5}
}

func (x *GetHistoryRequest) GetContactHash() string {
	if x != nil {
		return x.ContactHash
	}
	return ""
}

func (x *GetHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResponse) Reset() {
	*x = GetHistoryResponse{}
	mi := &file_cmd_webapi_grpc_proto_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResponse) ProtoMessage() {}

func (x *GetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_webapi_grpc_proto_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_cmd_webapi_grpc_proto_api_proto_rawDescGZIP(), []int{6}
}

func (x *GetHistoryResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsMe          bool                   `protobuf:"varint,1,opt,name=is_me,json=isMe,proto3" json:"is_me,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_cmd_webapi_grpc_proto_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_webapi_grpc_proto_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_cmd_webapi_grpc_proto_api_proto_rawDescGZIP(), []int{7}
}

func (x *Message) GetIsMe() bool {
	if x != nil {
		return x.IsMe
	}
	return false
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Message) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_cmd_webapi_grpc_proto_api_proto protoreflect.FileDescriptor

const file_cmd_webapi_grpc_proto_api_proto_rawDesc = "" +
	"\n" +
	"\x1fcmd/webapi_grpc/proto/api.proto\x12\vphantom.api\"Q\n" +
	"\x12SendMessageRequest\x12!\n" +
	"\fcontact_hash\x18\x01 \x01(\tR\vcontactHash\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"E\n" +
	"\x13SendMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x14\n" +
	"\x12GetContactsRequest\"G\n" +
	"\x13GetContactsResponse\x120\n" +
	"\bcontacts\x18\x01 \x03(\v2\x14.phantom.api.ContactR\bcontacts\"N\n" +
	"\aContact\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12\x1b\n" +
	"\tis_online\x18\x03 \x01(\bR\bisOnline\"L\n" +
	"\x11GetHistoryRequest\x12!\n" +
	"\fcontact_hash\x18\x01 \x01(\tR\vcontactHash\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"F\n" +
	"\x12GetHistoryResponse\x120\n" +
	"\bmessages\x18\x01 \x03(\v2\x14.phantom.api.MessageR\bmessages\"P\n" +
	"\aMessage\x12\x13\n" +
	"\x05is_me\x18\x01 \x01(\bR\x04isMe\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp2\x86\x02\n" +
	"\x11PhantomController\x12P\n" +
	"\vSendMessage\x12\x1f.phantom.api.SendMessageRequest\x1a .phantom.api.SendMessageResponse\x12P\n" +
	"\vGetContacts\x12\x1f.phantom.api.GetContactsRequest\x1a .phantom.api.GetContactsResponse\x12M\n" +
	"\n" +
	"GetHistory\x12\x1e.phantom.api.GetHistoryRequest\x1a\x1f.phantom.api.GetHistoryResponseB\x1fZ\x1dphantom/cmd/webapi_grpc/protob\x06proto3"

var (
	file_cmd_webapi_grpc_proto_api_proto_rawDescOnce sync.Once
	file_cmd_webapi_grpc_proto_api_proto_rawDescData []byte
)

func file_cmd_webapi_grpc_proto_api_proto_rawDescGZIP() []byte {
	file_cmd_webapi_grpc_proto_api_proto_rawDescOnce.Do(func() {
		file_cmd_webapi_grpc_proto_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_webapi_grpc_proto_api_proto_rawDesc), len(file_cmd_webapi_grpc_proto_api_proto_rawDesc)))
	})
	return file_cmd_webapi_grpc_proto_api_proto_rawDescData
}

var file_cmd_webapi_grpc_proto_api_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_cmd_webapi_grpc_proto_api_proto_goTypes = []any{
	(*SendMessageRequest)(nil),  // 0: phantom.api.SendMessageRequest
	(*SendMessageResponse)(nil), // 1: phantom.api.SendMessageResponse
	(*GetContactsRequest)(nil),  // 2: phantom.api.GetContactsRequest
	(*GetContactsResponse)(nil), // 3: phantom.api.GetContactsResponse
	(*Contact)(nil),             // 4: phantom.api.Contact
	(*GetHistoryRequest)(nil),   // 5: phantom.api.GetHistoryRequest
	(*GetHistoryResponse)(nil),  // 6: phantom.api.GetHistoryResponse
	(*Message)(nil),             // 7: phantom.api.Message
}
var file_cmd_webapi_grpc_proto_api_proto_depIdxs = []int32{
	4, // 0: phantom.api.GetContactsResponse.contacts:type_name -> phantom.api.Contact
	7, // 1: phantom.api.GetHistoryResponse.messages:type_name -> phantom.api.Message
	0, // 2: phantom.api.PhantomController.SendMessage:input_type -> phantom.api.SendMessageRequest
	2, // 3: phantom.api.PhantomController.GetContacts:input_type -> phantom.api.GetContactsRequest
	5, // 4: phantom.api.PhantomController.GetHistory:input_type -> phantom.api.GetHistoryRequest
	1, // 5: phantom.api.PhantomController.SendMessage:output_type -> phantom.api.SendMessageResponse
	3, // 6: phantom.api.PhantomController.GetContacts:output_type -> phantom.api.GetContactsResponse
	6, // 7: phantom.api.PhantomController.GetHistory:output_type -> phantom.api.GetHistoryResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cmd_webapi_grpc_proto_api_proto_init() }
func file_cmd_webapi_grpc_proto_api_proto_init() {
	if File_cmd_webapi_grpc_proto_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_webapi_grpc_proto_api_proto_rawDesc), len(file_cmd_webapi_grpc_proto_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_webapi_grpc_proto_api_proto_goTypes,
		DependencyIndexes: file_cmd_webapi_grpc_proto_api_proto_depIdxs,
		MessageInfos:      file_cmd_webapi_grpc_proto_api_proto_msgTypes,
	}.Build()
	File_cmd_webapi_grpc_proto_api_proto = out.File
	file_cmd_webapi_grpc_proto_api_proto_goTypes = nil
	file_cmd_webapi_grpc_proto_api_proto_depIdxs = nil
}
