// Copyright 2025 snaart
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.0
// source: proto/phantom.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SystemNotification_Type int32

const (
	SystemNotification_UNKNOWN          SystemNotification_Type = 0
	SystemNotification_DELIVERY_FAILURE SystemNotification_Type = 1
	SystemNotification_P2P_AVAILABLE    SystemNotification_Type = 2
	SystemNotification_P2P_PEER_INFO    SystemNotification_Type = 3
)

// Enum value maps for SystemNotification_Type.
var (
	SystemNotification_Type_name = map[int32]string{
		0: "UNKNOWN",
		1: "DELIVERY_FAILURE",
		2: "P2P_AVAILABLE",
		3: "P2P_PEER_INFO",
	}
	SystemNotification_Type_value = map[string]int32{
		"UNKNOWN":          0,
		"DELIVERY_FAILURE": 1,
		"P2P_AVAILABLE":    2,
		"P2P_PEER_INFO":    3,
	}
)

func (x SystemNotification_Type) Enum() *SystemNotification_Type {
	p := new(SystemNotification_Type)
	*p = x
	return p
}

func (x SystemNotification_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SystemNotification_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_phantom_proto_enumTypes[0].Descriptor()
}

func (SystemNotification_Type) Type() protoreflect.EnumType {
	return &file_proto_phantom_proto_enumTypes[0]
}

func (x SystemNotification_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SystemNotification_Type.Descriptor instead.
func (SystemNotification_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_phantom_proto_rawDescGZIP(), []int{5, 0}
}

// Контейнер верхнего уровня для всех типов сообщений
type Packet struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RoutingToken      []byte                 `protobuf:"bytes,1,opt,name=routing_token,json=routingToken,proto3" json:"routing_token,omitempty"`                  // 32 байта, токен маршрутизации (указывает на получателя)
	Signature         []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`                                            // Подпись Dilithium5 (подписывает payload)
	SenderIdentityKey []byte                 `protobuf:"bytes,3,opt,name=sender_identity_key,json=senderIdentityKey,proto3" json:"sender_identity_key,omitempty"` // Опционально: Публичный ключ отправителя (для первого сообщения/handshake)
	// Types that are valid to be assigned to Payload:
	//
	//	*Packet_RegistrationRequest
	//	*Packet_EncryptedMessage
	//	*Packet_SystemNotification
	//	*Packet_P2PUpdate
	Payload       isPacket_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_proto_phantom_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_phantom_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_proto_phantom_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetRoutingToken() []byte {
	if x != nil {
		return x.RoutingToken
	}
	return nil
}

func (x *Packet) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Packet) GetSenderIdentityKey() []byte {
	if x != nil {
		return x.SenderIdentityKey
	}
	return nil
}

func (x *Packet) GetPayload() isPacket_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Packet) GetRegistrationRequest() *RegistrationRequest {
	if x != nil {
		if x, ok := x.Payload.(*Packet_RegistrationRequest); ok {
			return x.RegistrationRequest
		}
	}
	return nil
}

func (x *Packet) GetEncryptedMessage() *EncryptedMessage {
	if x != nil {
		if x, ok := x.Payload.(*Packet_EncryptedMessage); ok {
			return x.EncryptedMessage
		}
	}
	return nil
}

func (x *Packet) GetSystemNotification() *SystemNotification {
	if x != nil {
		if x, ok := x.Payload.(*Packet_SystemNotification); ok {
			return x.SystemNotification
		}
	}
	return nil
}

func (x *Packet) GetP2PUpdate() *P2PUpdate {
	if x != nil {
		if x, ok := x.Payload.(*Packet_P2PUpdate); ok {
			return x.P2PUpdate
		}
	}
	return nil
}

type isPacket_Payload interface {
	isPacket_Payload()
}

type Packet_RegistrationRequest struct {
	RegistrationRequest *RegistrationRequest `protobuf:"bytes,4,opt,name=registration_request,json=registrationRequest,proto3,oneof"`
}

type Packet_EncryptedMessage struct {
	EncryptedMessage *EncryptedMessage `protobuf:"bytes,5,opt,name=encrypted_message,json=encryptedMessage,proto3,oneof"`
}

type Packet_SystemNotification struct {
	SystemNotification *SystemNotification `protobuf:"bytes,6,opt,name=system_notification,json=systemNotification,proto3,oneof"`
}

type Packet_P2PUpdate struct {
	P2PUpdate *P2PUpdate `protobuf:"bytes,7,opt,name=p2p_update,json=p2pUpdate,proto3,oneof"`
}

func (*Packet_RegistrationRequest) isPacket_Payload() {}

func (*Packet_EncryptedMessage) isPacket_Payload() {}

func (*Packet_SystemNotification) isPacket_Payload() {}

func (*Packet_P2PUpdate) isPacket_Payload() {}

type RegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListenTokens  [][]byte               `protobuf:"bytes,1,rep,name=listen_tokens,json=listenTokens,proto3" json:"listen_tokens,omitempty"` // Токены, на которые клиент хочет получать сообщения
	P2PInfo       *P2PInfo               `protobuf:"bytes,2,opt,name=p2p_info,json=p2pInfo,proto3" json:"p2p_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationRequest) Reset() {
	*x = RegistrationRequest{}
	mi := &file_proto_phantom_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationRequest) ProtoMessage() {}

func (x *RegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_phantom_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationRequest.ProtoReflect.Descriptor instead.
func (*RegistrationRequest) Descriptor() ([]byte, []int) {
	return file_proto_phantom_proto_rawDescGZIP(), []int{1}
}

func (x *RegistrationRequest) GetListenTokens() [][]byte {
	if x != nil {
		return x.ListenTokens
	}
	return nil
}

func (x *RegistrationRequest) GetP2PInfo() *P2PInfo {
	if x != nil {
		return x.P2PInfo
	}
	return nil
}

// Invite Bundle - структура, кодируемая в QR-код или ссылку
type Invite struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// --- PQC Ключи ---
	IdentityKeyDilithium []byte `protobuf:"bytes,1,opt,name=identity_key_dilithium,json=identityKeyDilithium,proto3" json:"identity_key_dilithium,omitempty"`
	IdentityKeyKyber     []byte `protobuf:"bytes,2,opt,name=identity_key_kyber,json=identityKeyKyber,proto3" json:"identity_key_kyber,omitempty"`
	SignedPrekeyKyber    []byte `protobuf:"bytes,3,opt,name=signed_prekey_kyber,json=signedPrekeyKyber,proto3" json:"signed_prekey_kyber,omitempty"`
	// --- Классические Ключи (X25519) ---
	IdentityKeyX25519        []byte `protobuf:"bytes,4,opt,name=identity_key_x25519,json=identityKeyX25519,proto3" json:"identity_key_x25519,omitempty"`
	SignedPrekeyX25519       []byte `protobuf:"bytes,5,opt,name=signed_prekey_x25519,json=signedPrekeyX25519,proto3" json:"signed_prekey_x25519,omitempty"`
	PrekeySignatureDilithium []byte `protobuf:"bytes,6,opt,name=prekey_signature_dilithium,json=prekeySignatureDilithium,proto3" json:"prekey_signature_dilithium,omitempty"`
	RoutingToken             []byte `protobuf:"bytes,7,opt,name=routing_token,json=routingToken,proto3" json:"routing_token,omitempty"` // Токен, который создатель инвайта слушает (для первого сообщения)
	DisplayName              string `protobuf:"bytes,8,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`    // Рекомендуемое имя (опционально)
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Invite) Reset() {
	*x = Invite{}
	mi := &file_proto_phantom_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invite) ProtoMessage() {}

func (x *Invite) ProtoReflect() protoreflect.Message {
	mi := &file_proto_phantom_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invite.ProtoReflect.Descriptor instead.
func (*Invite) Descriptor() ([]byte, []int) {
	return file_proto_phantom_proto_rawDescGZIP(), []int{2}
}

func (x *Invite) GetIdentityKeyDilithium() []byte {
	if x != nil {
		return x.IdentityKeyDilithium
	}
	return nil
}

func (x *Invite) GetIdentityKeyKyber() []byte {
	if x != nil {
		return x.IdentityKeyKyber
	}
	return nil
}

func (x *Invite) GetSignedPrekeyKyber() []byte {
	if x != nil {
		return x.SignedPrekeyKyber
	}
	return nil
}

func (x *Invite) GetIdentityKeyX25519() []byte {
	if x != nil {
		return x.IdentityKeyX25519
	}
	return nil
}

func (x *Invite) GetSignedPrekeyX25519() []byte {
	if x != nil {
		return x.SignedPrekeyX25519
	}
	return nil
}

func (x *Invite) GetPrekeySignatureDilithium() []byte {
	if x != nil {
		return x.PrekeySignatureDilithium
	}
	return nil
}

func (x *Invite) GetRoutingToken() []byte {
	if x != nil {
		return x.RoutingToken
	}
	return nil
}

func (x *Invite) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

// P2P информация о клиенте
type P2PInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`                    // libp2p peer ID
	Addresses     []string               `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`                            // multiaddr список
	PreferP2P     bool                   `protobuf:"varint,3,opt,name=prefer_p2p,json=preferP2p,proto3" json:"prefer_p2p,omitempty"`          // Предпочитает P2P
	RelayWilling  bool                   `protobuf:"varint,4,opt,name=relay_willing,json=relayWilling,proto3" json:"relay_willing,omitempty"` // Готов быть relay
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *P2PInfo) Reset() {
	*x = P2PInfo{}
	mi := &file_proto_phantom_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P2PInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P2PInfo) ProtoMessage() {}

func (x *P2PInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_phantom_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P2PInfo.ProtoReflect.Descriptor instead.
func (*P2PInfo) Descriptor() ([]byte, []int) {
	return file_proto_phantom_proto_rawDescGZIP(), []int{3}
}

func (x *P2PInfo) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *P2PInfo) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *P2PInfo) GetPreferP2P() bool {
	if x != nil {
		return x.PreferP2P
	}
	return false
}

func (x *P2PInfo) GetRelayWilling() bool {
	if x != nil {
		return x.RelayWilling
	}
	return false
}

type P2PUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []string               `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`                            // Обновленные адреса
	RelayWilling  bool                   `protobuf:"varint,2,opt,name=relay_willing,json=relayWilling,proto3" json:"relay_willing,omitempty"` // Статус relay
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *P2PUpdate) Reset() {
	*x = P2PUpdate{}
	mi := &file_proto_phantom_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P2PUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P2PUpdate) ProtoMessage() {}

func (x *P2PUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_phantom_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P2PUpdate.ProtoReflect.Descriptor instead.
func (*P2PUpdate) Descriptor() ([]byte, []int) {
	return file_proto_phantom_proto_rawDescGZIP(), []int{4}
}

func (x *P2PUpdate) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *P2PUpdate) GetRelayWilling() bool {
	if x != nil {
		return x.RelayWilling
	}
	return false
}

type SystemNotification struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Type          SystemNotification_Type `protobuf:"varint,1,opt,name=type,proto3,enum=proto.SystemNotification_Type" json:"type,omitempty"`
	Message       string                  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	P2PInfo       *P2PInfo                `protobuf:"bytes,3,opt,name=p2p_info,json=p2pInfo,proto3" json:"p2p_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemNotification) Reset() {
	*x = SystemNotification{}
	mi := &file_proto_phantom_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemNotification) ProtoMessage() {}

func (x *SystemNotification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_phantom_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemNotification.ProtoReflect.Descriptor instead.
func (*SystemNotification) Descriptor() ([]byte, []int) {
	return file_proto_phantom_proto_rawDescGZIP(), []int{5}
}

func (x *SystemNotification) GetType() SystemNotification_Type {
	if x != nil {
		return x.Type
	}
	return SystemNotification_UNKNOWN
}

func (x *SystemNotification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SystemNotification) GetP2PInfo() *P2PInfo {
	if x != nil {
		return x.P2PInfo
	}
	return nil
}

type EncryptedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RatchetHeader []byte                 `protobuf:"bytes,1,opt,name=ratchet_header,json=ratchetHeader,proto3" json:"ratchet_header,omitempty"`
	Ciphertext    []byte                 `protobuf:"bytes,2,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptedMessage) Reset() {
	*x = EncryptedMessage{}
	mi := &file_proto_phantom_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedMessage) ProtoMessage() {}

func (x *EncryptedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_phantom_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedMessage.ProtoReflect.Descriptor instead.
func (*EncryptedMessage) Descriptor() ([]byte, []int) {
	return file_proto_phantom_proto_rawDescGZIP(), []int{6}
}

func (x *EncryptedMessage) GetRatchetHeader() []byte {
	if x != nil {
		return x.RatchetHeader
	}
	return nil
}

func (x *EncryptedMessage) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *EncryptedMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// RPC для P2P (упрощенный)
type P2PInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoutingToken  []byte                 `protobuf:"bytes,1,opt,name=routing_token,json=routingToken,proto3" json:"routing_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *P2PInfoRequest) Reset() {
	*x = P2PInfoRequest{}
	mi := &file_proto_phantom_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P2PInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P2PInfoRequest) ProtoMessage() {}

func (x *P2PInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_phantom_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P2PInfoRequest.ProtoReflect.Descriptor instead.
func (*P2PInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_phantom_proto_rawDescGZIP(), []int{7}
}

func (x *P2PInfoRequest) GetRoutingToken() []byte {
	if x != nil {
		return x.RoutingToken
	}
	return nil
}

type P2PInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	PeerId        string                 `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Addresses     []string               `protobuf:"bytes,3,rep,name=addresses,proto3" json:"addresses,omitempty"`
	PreferP2P     bool                   `protobuf:"varint,4,opt,name=prefer_p2p,json=preferP2p,proto3" json:"prefer_p2p,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *P2PInfoResponse) Reset() {
	*x = P2PInfoResponse{}
	mi := &file_proto_phantom_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P2PInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P2PInfoResponse) ProtoMessage() {}

func (x *P2PInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_phantom_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P2PInfoResponse.ProtoReflect.Descriptor instead.
func (*P2PInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_phantom_proto_rawDescGZIP(), []int{8}
}

func (x *P2PInfoResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *P2PInfoResponse) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *P2PInfoResponse) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *P2PInfoResponse) GetPreferP2P() bool {
	if x != nil {
		return x.PreferP2P
	}
	return false
}

var File_proto_phantom_proto protoreflect.FileDescriptor

const file_proto_phantom_proto_rawDesc = "" +
	"\n" +
	"\x13proto/phantom.proto\x12\x05proto\"\xa0\x03\n" +
	"\x06Packet\x12#\n" +
	"\rrouting_token\x18\x01 \x01(\fR\froutingToken\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12.\n" +
	"\x13sender_identity_key\x18\x03 \x01(\fR\x11senderIdentityKey\x12O\n" +
	"\x14registration_request\x18\x04 \x01(\v2\x1a.proto.RegistrationRequestH\x00R\x13registrationRequest\x12F\n" +
	"\x11encrypted_message\x18\x05 \x01(\v2\x17.proto.EncryptedMessageH\x00R\x10encryptedMessage\x12L\n" +
	"\x13system_notification\x18\x06 \x01(\v2\x19.proto.SystemNotificationH\x00R\x12systemNotification\x121\n" +
	"\n" +
	"p2p_update\x18\a \x01(\v2\x10.proto.P2PUpdateH\x00R\tp2pUpdateB\t\n" +
	"\apayload\"e\n" +
	"\x13RegistrationRequest\x12#\n" +
	"\rlisten_tokens\x18\x01 \x03(\fR\flistenTokens\x12)\n" +
	"\bp2p_info\x18\x02 \x01(\v2\x0e.proto.P2PInfoR\ap2pInfo\"\x84\x03\n" +
	"\x06Invite\x124\n" +
	"\x16identity_key_dilithium\x18\x01 \x01(\fR\x14identityKeyDilithium\x12,\n" +
	"\x12identity_key_kyber\x18\x02 \x01(\fR\x10identityKeyKyber\x12.\n" +
	"\x13signed_prekey_kyber\x18\x03 \x01(\fR\x11signedPrekeyKyber\x12.\n" +
	"\x13identity_key_x25519\x18\x04 \x01(\fR\x11identityKeyX25519\x120\n" +
	"\x14signed_prekey_x25519\x18\x05 \x01(\fR\x12signedPrekeyX25519\x12<\n" +
	"\x1aprekey_signature_dilithium\x18\x06 \x01(\fR\x18prekeySignatureDilithium\x12#\n" +
	"\rrouting_token\x18\a \x01(\fR\froutingToken\x12!\n" +
	"\fdisplay_name\x18\b \x01(\tR\vdisplayName\"\x84\x01\n" +
	"\aP2PInfo\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x1c\n" +
	"\taddresses\x18\x02 \x03(\tR\taddresses\x12\x1d\n" +
	"\n" +
	"prefer_p2p\x18\x03 \x01(\bR\tpreferP2p\x12#\n" +
	"\rrelay_willing\x18\x04 \x01(\bR\frelayWilling\"N\n" +
	"\tP2PUpdate\x12\x1c\n" +
	"\taddresses\x18\x01 \x03(\tR\taddresses\x12#\n" +
	"\rrelay_willing\x18\x02 \x01(\bR\frelayWilling\"\xde\x01\n" +
	"\x12SystemNotification\x122\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1e.proto.SystemNotification.TypeR\x04type\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\bp2p_info\x18\x03 \x01(\v2\x0e.proto.P2PInfoR\ap2pInfo\"O\n" +
	"\x04Type\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x14\n" +
	"\x10DELIVERY_FAILURE\x10\x01\x12\x11\n" +
	"\rP2P_AVAILABLE\x10\x02\x12\x11\n" +
	"\rP2P_PEER_INFO\x10\x03\"w\n" +
	"\x10EncryptedMessage\x12%\n" +
	"\x0eratchet_header\x18\x01 \x01(\fR\rratchetHeader\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x02 \x01(\fR\n" +
	"ciphertext\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"5\n" +
	"\x0eP2PInfoRequest\x12#\n" +
	"\rrouting_token\x18\x01 \x01(\fR\froutingToken\"\x85\x01\n" +
	"\x0fP2PInfoResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\tR\x06peerId\x12\x1c\n" +
	"\taddresses\x18\x03 \x03(\tR\taddresses\x12\x1d\n" +
	"\n" +
	"prefer_p2p\x18\x04 \x01(\bR\tpreferP2p2C\n" +
	"\x04Auth\x12;\n" +
	"\n" +
	"GetP2PInfo\x12\x15.proto.P2PInfoRequest\x1a\x16.proto.P2PInfoResponse27\n" +
	"\aPhantom\x12,\n" +
	"\bTransmit\x12\r.proto.Packet\x1a\r.proto.Packet(\x010\x01B\x18Z\x16protocol_phantom/protob\x06proto3"

var (
	file_proto_phantom_proto_rawDescOnce sync.Once
	file_proto_phantom_proto_rawDescData []byte
)

func file_proto_phantom_proto_rawDescGZIP() []byte {
	file_proto_phantom_proto_rawDescOnce.Do(func() {
		file_proto_phantom_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_phantom_proto_rawDesc), len(file_proto_phantom_proto_rawDesc)))
	})
	return file_proto_phantom_proto_rawDescData
}

var file_proto_phantom_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_phantom_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_phantom_proto_goTypes = []any{
	(SystemNotification_Type)(0), // 0: proto.SystemNotification.Type
	(*Packet)(nil),               // 1: proto.Packet
	(*RegistrationRequest)(nil),  // 2: proto.RegistrationRequest
	(*Invite)(nil),               // 3: proto.Invite
	(*P2PInfo)(nil),              // 4: proto.P2PInfo
	(*P2PUpdate)(nil),            // 5: proto.P2PUpdate
	(*SystemNotification)(nil),   // 6: proto.SystemNotification
	(*EncryptedMessage)(nil),     // 7: proto.EncryptedMessage
	(*P2PInfoRequest)(nil),       // 8: proto.P2PInfoRequest
	(*P2PInfoResponse)(nil),      // 9: proto.P2PInfoResponse
}
var file_proto_phantom_proto_depIdxs = []int32{
	2, // 0: proto.Packet.registration_request:type_name -> proto.RegistrationRequest
	7, // 1: proto.Packet.encrypted_message:type_name -> proto.EncryptedMessage
	6, // 2: proto.Packet.system_notification:type_name -> proto.SystemNotification
	5, // 3: proto.Packet.p2p_update:type_name -> proto.P2PUpdate
	4, // 4: proto.RegistrationRequest.p2p_info:type_name -> proto.P2PInfo
	0, // 5: proto.SystemNotification.type:type_name -> proto.SystemNotification.Type
	4, // 6: proto.SystemNotification.p2p_info:type_name -> proto.P2PInfo
	8, // 7: proto.Auth.GetP2PInfo:input_type -> proto.P2PInfoRequest
	1, // 8: proto.Phantom.Transmit:input_type -> proto.Packet
	9, // 9: proto.Auth.GetP2PInfo:output_type -> proto.P2PInfoResponse
	1, // 10: proto.Phantom.Transmit:output_type -> proto.Packet
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_phantom_proto_init() }
func file_proto_phantom_proto_init() {
	if File_proto_phantom_proto != nil {
		return
	}
	file_proto_phantom_proto_msgTypes[0].OneofWrappers = []any{
		(*Packet_RegistrationRequest)(nil),
		(*Packet_EncryptedMessage)(nil),
		(*Packet_SystemNotification)(nil),
		(*Packet_P2PUpdate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_phantom_proto_rawDesc), len(file_proto_phantom_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_phantom_proto_goTypes,
		DependencyIndexes: file_proto_phantom_proto_depIdxs,
		EnumInfos:         file_proto_phantom_proto_enumTypes,
		MessageInfos:      file_proto_phantom_proto_msgTypes,
	}.Build()
	File_proto_phantom_proto = out.File
	file_proto_phantom_proto_goTypes = nil
	file_proto_phantom_proto_depIdxs = nil
}
